In [2]:
import numpy as np

In [53]:
board = np.array([
[1, 1, 1, 1, 1, 1, 1, 1],
[1, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 2, 2, 2, 2, 0, 0],
[1, 0, 2, 1, 1, 2, 0, 0],
[0, 0, 2, 1, 1, 2, 0, 0],
[0, 0, 2, 2, 2, 2, 0, 1],
[0, 1, 1, 1, 0, 0, 1, 1],
[1, 0, 1, 1, 1, 1, 1, 1]
])

In [3]:
board = np.array([
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 2, 0, 0, 0],
[0, 0, 0, 2, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0]
])

In [48]:
# stable[0,:] = 2
# stable[8,:] = 2
# stable[:,0] = 2
# stable[:,8] = 2
print(stable)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1.]]


In [4]:

#     for y in range(8):
#         if board[x][y] == 1:
#             pos = (x, y)
#             pos_next = pos
#             pos_s = (x + 1, y+1)
#             pos_s_next = pos_s
#             for d in directs:
#                 for i in range(8):
#                     pos_next += d
#                     if board[pos_next] == 1
stable = np.zeros((8, 8))
corners = [np.array([0, 0]),np.array([0, 7]),np.array([7, 0]),np.array([7, 7])]   
directions_list = np.array([[np.array([0, 1]),np.array([1, 0]),np.array([1, 1])],
          [np.array([0, -1]),np.array([1, 0]),np.array([1, -1])],
          [np.array([0, 1]),np.array([-1, 0]),np.array([-1, 1])],
          [np.array([0, -1]),np.array([-1, 0]),np.array([-1, -1])]])
# for x in range(8):
for idx, c in enumerate(corners):
    if board[(*c,)] == 1:
        stable[(*c,)] = 1
        directions = directions_list[idx]
        count = 0
        for d in directions[0:2]:
            pos_next = c + d
            for i in range(7):
                if board[(*pos_next,)] == 1:
                    stable[(*pos_next,)] = 1
                else:
                    break
                pos_next += d
print(stable)
for j in range(3): 
    corners[0] += (1,1)   
    corners[1] += (1,-1)
    corners[2] += (-1,1)
    corners[3] += (-1,-1)
    for idx, c in enumerate(corners):
        print('idx, c', idx, c)
        if board[(*c,)] == 1:
            directions = directions_list[idx]
            count = 0
            for d in directions:
                if stable[(*(c - d),)] != 1:
                    print('break', c)
                    count= 0
                    break
                count += 1
            if count == 3:
                stable[(*c,)] = 1
                print('stable[(*c,)] = 1', c)
                for d in directions[0:2]:
                    pos_next = c + d
                    for i in range(7):
                        if board[(*pos_next,)] == 1:
                            stable[(*pos_next,)] = 1
                            if list(pos_next) == [6, 1]:
                                print('[6, 1]: ', c, d)
                        else:
                            break
                        pos_next += d            
            
            
            

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
idx, c 0 [1 1]
idx, c 1 [1 6]
idx, c 2 [6 1]
idx, c 3 [6 6]
idx, c 0 [2 2]
idx, c 1 [2 5]
idx, c 2 [5 2]
idx, c 3 [5 5]
idx, c 0 [3 3]
break [3 3]
idx, c 1 [3 4]
idx, c 2 [4 3]
idx, c 3 [4 4]
break [4 4]


In [5]:
stable

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
stable[(*(c - d),)]

1.0

In [73]:
directions[0:2]

array([[ 0, -1],
       [-1,  0]])

In [81]:
 corners[0]

array([3, 3])